spring:
  application:
    name:
      GoFarBot
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driverClassName: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
bot:
  name:
    ${TG_BOT_NAME}
  token:
    ${TG_BOT_TOKEN}
minio:
  url: ${MINIO_URL}
  access:
    name: ${MINIO_ACCESS_KEY}
    secret: ${MINIO_SECRET_KEY}
  buckets:
    documents: documents
    photos: photos
logging:
  file:
    path: classpath
    name: Logging.log
  level:
    root: INFO
    org.springframework.security: DEBUG