spring:
  application:
    name:
      GoFarBot
  datasource:
    url: jdbc:postgresql://localhost:5432/gofar
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
bot:
  name:
    goFarBot_localtest
  token:
    7552669377:AAGUcPS0aZRQ2EfMHG9VyS7I71Eog9NAtlk
minio:
  url: http://localhost:9000
  access:
    name: ZYPRYMQmxFdH4KmWQwtW
    secret: MCLskXbhNiHLfqAweJpwQB4QYnhDsBvIvTBl9ZUm
  buckets:
    documents: documents
    photos: photos
logging:
  file:
    path: classpath
    name: Logging.log
  level:
    root: INFO
    org.springframework.security: DEBUG