spring:
  application:
    name:
      GoFarBot
  datasource:
    url: jdbc:postgresql://localhost:5432/gofar
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
bot:
  name:
    goFarBot_test-development-version
  token:
    7365748376:AAHTagw_pBibRMuUmEsI_drRzvyFp3a0eKU
minio:
  url: http://localhost:9000
  access:
    name: ${MINIO_ACCESS_KEY}
    secret: ${MINIO_SECRET_KEY}
  buckets:
    documents: documents
    photos: photos
logging:
  file:
    path: classpath
    name: Logging.log
  level:
    root: INFO
    org.springframework.security: DEBUG