databaseChangeLog:
  - changeSet:
      id: 9
      author: vsevolod schetov
      changes:
        - insert:
            tableName: messages
            columns:
              - column:
                  name: number
                  value: 1
              - column:
                  name: text
                  value: |
                    Привет! Спасибо что присоединился к нам 😉 
                    скоро у нас пройдет трехдневный вебинар о подготовке и поступлении в Австрию в 2025 году
                    регистрируйся по специальной кнопке снизу 👇🏻
              - column:
                  name: dialog
                  value: 1