databaseChangeLog:
  - changeSet:
      id: 21
      author: vsevolod schetov
      changes:
        - insert:
            tableName: files
            columns:
              - column:
                  name: link
                  value: TestImage.png
              - column:
                  name: type
                  value: PHOTO
        - insert:
            tableName: files
            columns:
              - column:
                  name: link
                  value: Resume.pdf
              - column:
                  name: type
                  value: DOCUMENT
        - insert:
            tableName: files
            columns:
              - column:
                  name: link
                  value: 01.png
              - column:
                  name: type
                  value: PHOTO
        - insert:
            tableName: files
            columns:
              - column:
                  name: link
                  value: 02.png
              - column:
                  name: type
                  value: PHOTO
        - insert:
            tableName: files
            columns:
              - column:
                  name: link
                  value: 03.png
              - column:
                  name: type
                  value: PHOTO