databaseChangeLog:
  - changeSet:
      id: 11
      author: vsevolod schetov
      changes:
        - insert:
            tableName: messages
            columns:
              - column:
                  name: number
                  value: 1
              - column:
                  name: text
                  value: Какую информацию о поступлении ты хочешь узнать?
              - column:
                  name: dialog
                  value: 3
        - insert:
            tableName: messages
            columns:
              - column:
                  name: number
                  value: 2
              - column:
                  name: text
                  value: Про какую страну ты хочешь узнать больше?
              - column:
                  name: dialog
                  value: 3
        #Материалы по странам
        - insert:
            tableName: messages
            columns:
              - column:
                  name: number
                  value: 3
              - column:
                  name: text
                  value: |
                    Лови информацию про Австрию
                    
                    Планируешь поступать? Заполняй анкету и приходи на бесплатную консультацию по поступлению - https://forms.gle/4229Xqs9WS53RY447
              - column:
                  name: dialog
                  value: 3
        - insert:
            tableName: links
            columns:
              - column:
                  name: type
                  value: 1
              - column:
                  name: value
                  value: Это ссылка на видео по Австрии
        - insert:
            tableName: messages_links_rel
            columns:
              - column:
                  name: message
                  value: 4
              - column:
                  name: link
                  value: 1

        - insert:
            tableName: messages
            columns:
              - column:
                  name: number
                  value: 4
              - column:
                  name: text
                  value: |
                    Лови информацию про Германию
                    Планируешь поступать? Заполняй анкету и приходи на бесплатную консультацию по поступлению - https://forms.gle/4229Xqs9WS53RY447
              - column:
                  name: dialog
                  value: 3
        - insert:
            tableName: links
            columns:
              - column:
                  name: type
                  value: 1
              - column:
                  name: value
                  value: Это ссылка на видео по Германии
        - insert:
            tableName: messages_links_rel
            columns:
              - column:
                  name: message
                  value: 5
              - column:
                  name: link
                  value: 2

        - insert:
            tableName: messages
            columns:
              - column:
                  name: number
                  value: 5
              - column:
                  name: text
                  value: |
                    Лови информацию про Италию
                    Планируешь поступать? Заполняй анкету и приходи на бесплатную консультацию по поступлению - https://forms.gle/4229Xqs9WS53RY447
              - column:
                  name: dialog
                  value: 3
        - insert:
            tableName: links
            columns:
              - column:
                  name: type
                  value: 1
              - column:
                  name: value
                  value: Это ссылка на видео по Италии
        - insert:
            tableName: messages_links_rel
            columns:
              - column:
                  name: message
                  value: 6
              - column:
                  name: link
                  value: 3
        #Ссылки на соц. сети
        - insert:
            tableName: messages
            columns:
              - column:
                  name: number
                  value: 6
              - column:
                  name: text
                  value: |
                    GoFar - помощь с поступлением в вузы Европы:
                    Сайт - https://letsgofar.eu/
                    Instagram - https://www.instagram.com/gofar_ru?igsh=ZXVjbW5zamw5aXc4
                    Telegram-канал - https://t.me/gofareu
                    Telegram-чат - https://t.me/gofarchat
                    YouTube - https://www.youtube.com/@letsgofaryt
                    ВКонтакете - https://vk.com/letsgofar

                    Школа подготовки к сдаче языковых экзаменов GoLearn:
                    Instagram - https://www.instagram.com/golearn_eu?igsh=MXZ1N3lvYTc3cXMxag==
                    Telegram-канал - https://t.me/gofareu
                    Telegram-чат - 
                    ВКонтакте - https://vk.com/golearn_eu
              - column:
                  name: dialog
                  value: 3
        - insert:
            tableName: links
            columns:
              - column:
                  name: type
                  value: 1
              - column:
                  name: value
                  value: Это ссылка на ютуб канал
        - insert:
            tableName: links
            columns:
              - column:
                  name: type
                  value: 2
              - column:
                  name: value
                  value: Это ссылка на тг канал
        - insert:
            tableName: links
            columns:
              - column:
                  name: type
                  value: 3
              - column:
                  name: value
                  value: Это ссылка на инсту
        - insert:
            tableName: links
            columns:
              - column:
                  name: type
                  value: 4
              - column:
                  name: value
                  value: Это ссылка на ВК
        #Задать вопрос
        - insert:
            tableName: messages
            columns:
              - column:
                  name: number
                  value: 7
              - column:
                  name: text
                  value: |
                    GoFar - помощь с поступлением в вузы Европы:
                    Сайт - https://letsgofar.eu/
                    Instagram - https://www.instagram.com/gofar_ru?igsh=ZXVjbW5zamw5aXc4
                    Telegram-канал - https://t.me/gofareu
                    Telegram-чат - https://t.me/gofarchat
                    YouTube - https://www.youtube.com/@letsgofaryt
                    ВКонтакете - https://vk.com/letsgofar

                    Школа подготовки к сдаче языковых экзаменов GoLearn:
                    Instagram - https://www.instagram.com/golearn_eu?igsh=MXZ1N3lvYTc3cXMxag==
                    Telegram-канал - https://t.me/gofareu
                    Telegram-чат - 
                    ВКонтакте - https://vk.com/golearn_eu
              - column:
                  name: dialog
                  value: 3