databaseChangeLog:
  - changeSet:
      id: 19
      author: vsevolod schetov
      changes:
        - insert:
            tableName: notifications
            columns:
              - column:
                  name: text
                  value: |
                    🔔Напоминаем, уже завтра 4.10 в 18:00 по МСК состоится вебинар "Самый легкий способ релокации. Поступление в Австрию без знания языка"
                    Поговорим о том как подготовиться к поступлению и поступить. Расскажем что вас ждет на языковых курсах. Все об обучении: стоимость, длительность, вступительные и выпускные экзамены. Дальнейшие действия после окончание курсов: поступление на бакалавриат, магистратуру или подготовительные курсы😉

                    Ссылку на подключение жди завтра, отправим в этот чат перед началом вебинара

                    Перед вебинаром команда кураторов по Австрии традиционно просит вас заполнить анкету 👉🏻 https://forms.gle/yWzJcwQLeDHSRZJt6
                    Ваши ответы помогут нам сделать встречу максимально информативной ❤️
                    Для всех участников встречи мы подготовили файл со всеми популярными программами, вузами и городами Австрии 🔥 отправим его в этот чат после вебинар
              - column:
                  name: type
                  value: 1
        - insert:
            tableName: notifications
            columns:
              - column:
                  name: text
                  value: |
                    Привет! Напоминаем, что сегодня в 18:00 состоится первые вебинар о поступлении в Австрию 🇦🇹
                    Не пропусти важну информацию о поступлении на подготовительные/языковые курсы, бакалавриат и магистратуру без знания языка
              - column:
                  name: type
                  value: 2
        - insert:
            tableName: notifications
            columns:
              - column:
                  name: text
                  value: Мы начинаем через час 🕡 лови свою ссылку на подключение - test_link
              - column:
                  name: type
                  value: 3
        - insert:
            tableName: notifications
            columns:
              - column:
                  name: text
                  value: |
                    Мы начинаем! 🔥☺️ Подключайся скорее по ссылке - test_link
                    
                    Мы уже начали рассматривать финансовые аспекты поступления 💳 считаем сколько денег нужно для поступления в страну
                    Присоединяйся!
                    
                    Согласись, обидно пройти большой путь, поступить и приехать в страну и провалить вступительные испытания? Прямо сейчас Кирилл рассказывает как подготовиться к сдаче экзамена, как он будет проходить, как показать "лучший немецкий" и гарантировать себе место в вузе
                    Присоединяйся 😉
              - column:
                  name: type
                  value: 4
        - insert:
            tableName: notifications
            columns:
              - column:
                  name: text
                  value: |
                    Спасибо что подключился! ❤️ лови обещанную анкету на бесплатную консультацию (ссылка на анкету)
                    Если тебе интересно узнать больше о подготовке вместе с командой GoLearn, то переходи по кнопке ниже и оставляй заявку на бесплатную консультацию по подготовке к поступлению у методиста (добавить кнопку "Бесплатная консультация от методиста GoLearn"
              - column:
                  name: type
                  value: 5
        - insert:
            tableName: notifications
            columns:
              - column:
                  name: text
                  value: |
                    🔗Лови обещанный файл. Тут расписаны самые популярные программы и направления подготовки в вузах Австрии 🧑🏼‍🎓 выбирай подходящее направление и готовься к нашему вебинар через неделю!
                    На следующей встрече мы разберем все что касается обучения на бакалавриат и магистратуре.Обучение на немецком и английском. Дедлайны на подачу в университеты и документы, которые понадобятся для поступления
              - column:
                  name: type
                  value: 6