databaseChangeLog:
  - changeSet:
      id: 21
      author: vsevolod schetov
      changes:
        - insert:
            tableName: messages
            columns:
              - column:
                  name: number
                  value: 1
              - column:
                  name: text
                  value: |
                    Ты успешно зарегистрировался на серию вебинаров "Как поступить в Австрию в 2025 году"

                    Трансляция будет проходить в (название платформы).  Предварительная регистрация на платформе для участия не требуется
                    В день вебинара мы отправим ссылку на подключение в этот чат 🔗

                    Календарь видео-встреч:

                    🗓 04.10 (пятница) в 18:00 по МСК -  Поступление без знания языка. Самый простой способ релокации в Европу для школьников и студентов РФ и СНГ

                    🗓 05.10 (суббота) в 18:00 по МСК  - Поступление в университет на бакалавриат и магистратуру. Обучение на английском и немецком языке

                    🗓 06.10 (воскресенье) в 18:00 по МСК  - Практика и работа во время и после обучения. Все о жизни студента и о перспективах

                    После участия во всех 3-х вебинарах ты:
                    - будешь понимать, какой путь тебе предстоит пройти от идеи поступить до получения диплома в стране
                    - узнаешь сколько будет стоить обучение и жизнь в Австрии
                    - какие документы нужно собрать, сколько они готовятся и когда нужно начинать подготовку в зависимости от того, куда ты планируешь поступать
                    - выберешь специальность, направление подготовки и будущий город обучения. Узнаешь все о студенческой жизни в выбранном городе
                    - построишь индивидуальный план поступления в зависимости от города и специальности
              - column:
                  name: dialog
                  value: 2
        - insert:
            tableName: messages
            columns:
              - column:
                  name: number
                  value: 2
              - column:
                  name: text
                  value: |
                    Забирай обещанный подарок за регистрацию: Полный файл по подготовке и поступлению в Австрию 🎁 (прикрепить файл)
                    - нюансы поступления на бакалавриат и магистратуру
                    - этапы подготовки к поступлению
                    - стоимость обучения и проживания
                    - работа для студентов
                    - все о документах для поступления
                    - перспективы после окончания обучения
              - column:
                  name: dialog
                  value: 2
        - insert:
            tableName: messages
            columns:
              - column:
                  name: number
                  value: 3
              - column:
                  name: text
                  value: |
                    Есть вопросы по поступлению и подготовке? Можешь задать их прямо сейчас, заходи в наш Telegram-чат 👉🏻 https://t.me/gofarchat

                    Также подписывайся на соц.сети агентства помощи с поступлением, обещаем ты найдешь много интересного 😉
                    YouTube - https://www.youtube.com/@letsgofaryt
                    Telegram-канал - https://t.me/gofareu
                    ВКонтакте - https://vk.com/letsgofar
              - column:
                  name: dialog
                  value: 2
        - insert:
            tableName: messages
            columns:
              - column:
                  name: number
                  value: 4
              - column:
                  name: text
                  value: |
                    Смотри повтор серии вебинаров "Как поступить в Австрию в 2025 году"

                    🗓 Часть 1: Поступление без знания языка. Самый простой способ релокации в Европу для школьников и студентов РФ и СНГ

                    🗓 Часть 2: Поступление в университет на бакалавриат и магистратуру. Обучение на английском и немецком языке

                    🗓 Часть 3:  Практика и работа во время и после обучения. Все о жизни студента и о перспективах


                    После участия во всех 3-х вебинарах ты:
                    - будешь понимать какой путь тебе предстоит пройти от идеи поступить до получения диплома в стране
                    - узнаешь сколько будет стоить обучение и жизнь в Австрии
                    - какие документы нужно собрать, сколько они готовятся и когда нужно начинать подготовку в зависимости от того куда ты планируешь поступать
                    - выберешь специальность, направление подготовки и будущий город обучения. Узнаешь все о студенческой жизни в выбранном городе
                    - построишь индивидуальный план поступления в зависимости от города и специальности
              - column:
                  name: dialog
                  value: 2
        - insert:
            tableName: messages
            columns:
              - column:
                  name: number
                  value: 5
              - column:
                  name: text
                  value: |
                    Есть вопросы по поступлению и подготовке? Можешь задать их прямо сейчас, заходи в наш Telegram-чат 👉🏻 https://t.me/gofarchat

                    Также подписывайся на соц.сети агентства помощи с поступлением, обещаем ты найдешь много интересного 😉
                    YouTube - https://www.youtube.com/@letsgofaryt
                    Telegram-канал - https://t.me/gofareu
                    ВКонтакте - https://vk.com/letsgofar
              - column:
                  name: dialog
                  value: 2
        - insert:
            tableName: messages
            columns:
              - column:
                  name: number
                  value: 6
              - column:
                  name: text
                  value: |
                    Лови обещанную ссылку на запись вебинаров - test_link
              - column:
                  name: dialog
                  value: 2