databaseChangeLog:
  - changeSet:
      id: 19
      author: vsevolod schetov
      changes:
        - insert:
            tableName: notifications
            columns:
              - column:
                  name: text
                  value: |
                    Привет! Серия вебинаров по Австрии, которую ты так долго ждал, стартует уже **ЗАВТРА в 18.00 по МСК / 20.00 по Астане и Ташкенту** 🔥

                    Освобождай следующие три вечера и присоединяйся к нам на интенсив 📆

                    Наш многолетний опыт учебы в Австрии и истории десятков проведённых нами клиентов мы сконцентрировали <b><u>в 3 сессиях по 1,5 часа</u></b> 💯

                    Увидимся уже завтра!
              - column:
                  name: type
                  value: 1
        - insert:
            tableName: notifications
            columns:
              - column:
                  name: text
                  value: |
                    Отсчёт пошёл, ровно **ЧЕРЕЗ ЧАС** стартует наш первый вебинар: «Самый простой способ релокации. Поступление без знания языка» 🕡 Лови ссылку на подключение – test_link!!!😎
              - column:
                  name: type
                  value: 3
              - column:
                  name: file
                  value: 3
        - insert:
            tableName: notifications
            columns:
              - column:
                  name: text
                  value: |
                    **МЫ НАЧИНАЕМ!** 🔥☺️ Подключайся скорее по ссылке – test_link
              - column:
                  name: type
                  value: 4
        - insert:
            tableName: notifications
            columns:
              - column:
                  name: text
                  value: |
                    **СПАСИБО**, что подключился! ❤️ Если не успел заполнить анкету во время вебинара, **ЗАПОЛНЯЙ ЗАЯВКУ** на нашем сайте: https://letsgofar.eu/
              - column:
                  name: type
                  value: 5
        - insert:
            tableName: notifications
            columns:
              - column:
                  name: text
                  value: |
                    Немецкие ученые определили, что студенты запоминают лишь 20% информации, которую слышат. Поэтому мы подготовили для тебя шпаргалку, где собрали все важную информацию о подготовительных курсах!
                    Ждём тебя завтра на втором вебинаре, где мы расскажем про поступление на бакалавриат и магистратуру и дадим тонну лайфхаков по подготовке 😉
              - column:
                  name: type
                  value: 6
              - column:
                  name: file
                  value: 7
        - insert:
            tableName: notifications
            columns:
              - column:
                  name: text
                  value: |
                    Отсчёт пошёл, ровно **ЧЕРЕЗ ЧАС** стартует наш второй вебинар про поступление на бакалавриат и магистратуру в Австрии 🕡 Лови ссылку на подключение – test_link!!!😎
              - column:
                  name: type
                  value: 3
              - column:
                  name: file
                  value: 4
        - insert:
            tableName: notifications
            columns:
              - column:
                  name: text
                  value: |
                    **МЫ НАЧИНАЕМ!** 🔥☺️ Подключайся скорее по ссылке – test_link
              - column:
                  name: type
                  value: 4
        - insert:
            tableName: notifications
            columns:
              - column:
                  name: text
                  value: |
                    **СПАСИБО**, что подключился! ❤️ Если не успел заполнить анкету во время вебинара, **ЗАПОЛНЯЙ ЗАЯВКУ** на нашем сайте: https://letsgofar.eu/
              - column:
                  name: type
                  value: 5
        - insert:
            tableName: notifications
            columns:
              - column:
                  name: text
                  value: |
                    🔗 Лови обещанный гайд по мотивационным письмам для подачи в вузы Европы 🧑🏼‍🎓 

                    Готовься к нашему завтрашнему вебинару, где ты узнаешь, как выглядит **СИСТЕМА ОБУЧЕНИЯ** австрийских студентов, а также про **ВНЖ** и **КАРЬЕРНЫЕ ПЕРСПЕКТИВЫ!**
              - column:
                  name: type
                  value: 6
              - column:
                  name: file
                  value: 8
        - insert:
            tableName: notifications
            columns:
              - column:
                  name: text
                  value: |
                    Отсчёт пошёл, ровно **ЧЕРЕЗ ЧАС** стартует наш третий вебинар «Работа для студентов. Все о жизни студентов и перспективах» 🕡 Лови ссылку на подключение – test_link!!!😎
              - column:
                  name: type
                  value: 3
        - insert:
            tableName: notifications
            columns:
              - column:
                  name: text
                  value: |
                    **МЫ НАЧИНАЕМ!** 🔥☺️ Подключайся скорее по ссылке – test_link
              - column:
                  name: type
                  value: 4
        - insert:
            tableName: notifications
            columns:
              - column:
                  name: text
                  value: |
                    СПАСИБО, что подключился! ❤️ Если не успел заполнить анкету во время вебинара, ЗАПОЛНЯЙ ЗАЯВКУ на нашем сайте: https://letsgofar.eu/

                    За эти три дня мы выдали много информации об Австрии и поступлении туда. Лови краткую выжимку, где мы собрали всю самую важную и актуальную информацию
              - column:
                  name: type
                  value: 5
              - column:
                  name: file
                  value: 9